# Generated by Django 3.0.4 on 2020-04-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
